test:
  script:
    - cargo fmt -- --check
    - cargo clippy --target-dir=../target -- -D warnings
    - cargo clippy --target-dir=../target --all-features -- -D warnings
    - cargo test --target-dir=../target --all-features
  only:
    - branches

stages:
  - test
