image: "rust:latest"

test:
  before_script:
    - rustup component add rustfmt
    - rustup component add clippy
  script:
    - cargo fmt -- --check
    - cargo test --features proxy
    - cargo clippy
    - cargo clippy --features proxy
  only:
    - branches

stages:
  - test
