image: "rust:latest"

test:
  before_script:
    - rustup component add rustfmt
    - rustup component add clippy
  script:
    - cargo fmt -- --check
    - cargo clippy -- -D warnings
    - cargo clippy --all-features -- -D warnings
    - cargo test --all-features
  only:
    - branches

stages:
  - test
