test:
  script:
    - cargo fmt -- --check
    - cargo clippy --target-dir=../target -- -D warnings
    - cargo clippy --target-dir=../target --all-features -- -D warnings
    - cargo test --target-dir=../target --all-features
  only:
    - branches

pages:
  script:
    - cargo doc --target-dir=../target
    - mv ../target ./public
  artifacts:
    paths:
      - public
  only:
    - branches #TODO: change to master before merge

stages:
  - test
  - pages
