check-formatting:
    stage: test
    script:
        - cargo fmt -- --check
    only:
        - branches

run-clippy:
    stage: test
    script:
        - cargo clippy --target-dir=../target --examples --no-default-features --features "tokio/macros tls" -- -D warnings
        - cargo clippy --target-dir=../target --examples --no-default-features --features "tokio/macros rustls" -- -D warnings
        - cargo clippy --target-dir=../target --examples --features "tokio/macros proxy" -- -D warnings
    only:
        - branches

run-tests:
    stage: test
    script:
        - cargo test --target-dir=../target --features="proxy"
    only:
        - branches

generate-master-docs:
    stage: docs
    script:
        - cargo doc --release --no-deps --target-dir=../target
        - mv ../target/doc ./public
        - echo '<meta http-equiv="refresh" content="0; url=./tbot/index.html">' > ./public/index.html
    artifacts:
        paths:
            - public
    only:
        - master

stages:
    - test
    - docs
