[package]
name = "tbot"
version = "0.2.2"
description = "Make cool Telegram bots with Rust easily."
repository = "https://gitlab.com/SnejUgal/tbot"
readme = "./readme.md"
license = "MIT"
authors = [
  "SnejUgal <snejugal@icloud.com>",
  "AlexStrNik (t.me/AlexStrNik)",
]
edition = "2018"
keywords = [
    "telegram",
]
categories = [
    "api-bindings",
    "asynchronous",
]

[dependencies]
hyper = "=0.13.0-alpha.4"
hyper-tls = "=0.4.0-alpha.4"
hyper-proxy = { version = "0.5", optional = true, features = [] }
tokio = "=0.2.0-alpha.6"
serde_json = "1"
serde = { version = "1.0.34", features = ["derive"] }
tokio-tls = "=0.3.0-alpha.6"
native-tls = "0.2.3"

[dev-dependencies]
meval = "0.2"

[features]
proxy = ["hyper-proxy"]
