[package]
name = "tbot"
version = "0.1.0"
authors = [
  "SnejUgal <snejugal@icloud.com>",
]
edition = "2018"

[dependencies]
hyper = "0.12.11"
hyper-tls = "0.3.1"
hyper-proxy = { version = "0.4.1", optional = true }
tokio = "0.1.11"
futures = "0.1.24"
serde_json = "1.0.32"
serde = "1.0.79"
serde_derive = "1.0.79"

[features]
proxy = ["hyper-proxy"]
