[package]
name = "tbot"
version = "0.1.0"
authors = [
  "SnejUgal <snejugal@icloud.com>",
  "AlexStrNik (t.me/AlexStrNik)",
]
edition = "2018"

[dependencies]
hyper = "0.12"
hyper-tls = "0.3"
hyper-proxy = { version = "0.5", optional = true, features = [] }
tokio = "0.1.11"
futures = "0.1.24"
serde_json = "1.0.32"
serde = { version = "1.0.79", features = ["derive"] }
rand = "0.6"

[dev-dependencies]
meval = "0.2"

[features]
proxy = ["hyper-proxy"]
