[package]
name = "tbot"
version = "0.2.0"
description = "Make cool Telegram bots with Rust easily."
repository = "https://gitlab.com/SnejUgal/tbot"
readme = "./readme.md"
license = "MIT"
authors = [
  "SnejUgal <snejugal@icloud.com>",
  "AlexStrNik (t.me/AlexStrNik)",
]
edition = "2018"
keywords = [
    "telegram",
]
categories = [
    "api-bindings",
    "asynchronous",
]

[dependencies]
hyper = "0.12"
hyper-tls = "0.3"
hyper-proxy = { version = "0.5", optional = true, features = [] }
tokio = "0.1.8"
futures = "0.1.23"
serde_json = "1"
serde = { version = "1.0.34", features = ["derive"] }
num_cpus = "1.2"

[dev-dependencies]
meval = "0.2"

[features]
proxy = ["hyper-proxy"]
