[package]
name = "tbot"
version = "0.2.2"
description = "Make cool Telegram bots with Rust easily."
repository = "https://gitlab.com/SnejUgal/tbot"
readme = "./readme.md"
license = "MIT"
authors = [
  "SnejUgal <snejugal@icloud.com>",
  "AlexStrNik (t.me/AlexStrNik)",
]
edition = "2018"
keywords = [
    "telegram",
]
categories = [
    "api-bindings",
    "asynchronous",
]

[dependencies]
hyper = { version = "0.13", default-features = false }
hyper-tls = "0.4"
hyper-proxy = { version = "0.6", optional = true }
tokio = { version = "0.2", features = ["time", "rt-core", "tcp"] }
serde_json = "1"
serde = { version = "1.0.34", features = ["derive"] }
tokio-tls = "0.3"
native-tls = "0.2"

[dev-dependencies]
meval = "0.2"

[features]
proxy = ["hyper-proxy"]

[[example]]
name = "attachments"
required-features = ["tokio/macros"]

[[example]]
name = "download"
required-features = ["tokio/macros"]

[[example]]
name = "game"
required-features = ["tokio/macros", "tokio/sync"]

[[example]]
name = "get_me"
required-features = ["tokio/macros"]

[[example]]
name = "keyboard"
required-features = ["tokio/macros"]

[[example]]
name = "location"
required-features = ["tokio/macros"]

[[example]]
name = "payment"
required-features = ["tokio/macros"]

[[example]]
name = "polls"
required-features = ["tokio/macros"]

[[example]]
name = "proxy"
required-features = ["tokio/macros", "proxy"]

[[example]]
name = "sticker_packs"
required-features = ["tokio/macros"]

[[example]]
name = "tutorial"
required-features = ["tokio/macros", "tokio/sync"]

[[example]]
name = "webhook"
required-features = ["tokio/macros"]
